#include "PIC14CodeGen.h"
#include <format>
#include <utility>
#include <variant>
#include <iostream>

#include "backend/analysis/StackAllocator.h"

PIC14CodeGen::PIC14CodeGen(DeviceConfig  cfg) : config(std::move(cfg)), out(nullptr) {
    label_counter = 0;
    ram_head = 0x20;
}

std::string PIC14CodeGen::resolve_address(const tacky::Val& val) {
    if (const auto c = std::get_if<tacky::Constant>(&val)) {
        return std::format("0x{:02X}", c->value & 0xFF);
    }
    if (const auto mem = std::get_if<tacky::MemoryAddress>(&val)) {
        return std::format("0x{:02X}", mem->address);
    }

    std::string name;
    if (const auto v = std::get_if<tacky::Variable>(&val)) name = v->name;
    else if (const auto t = std::get_if<tacky::Temporary>(&val)) name = t->name;

    if (stack_layout.contains(name)) {
        return name;
    }

    return get_or_alloc_variable(name);
}

std::string PIC14CodeGen::get_or_alloc_variable(const std::string& name) {
    if (!symbol_table.contains(name)) {
        symbol_table[name] = ram_head++;
        emit_raw(std::format("{} EQU 0x{:02X}", name, symbol_table[name]));
    }
    return name;
}

void PIC14CodeGen::select_bank(const std::string& operand) {
    try {
        if (operand.size() > 2 && operand.substr(0, 2) == "0x") {
            int addr = std::stoi(operand, nullptr, 16);

            const int new_bank = (addr >> 7) & 0x03;
            if (current_bank == new_bank) return;

            if (new_bank & 1) emit("BSF", "STATUS, 5"); else emit("BCF", "STATUS, 5"); // RP0
            if (new_bank & 2) emit("BSF", "STATUS, 6"); else emit("BCF", "STATUS, 6"); // RP1
            current_bank = new_bank;
        }
    } catch (...) {
    }
}

void PIC14CodeGen::emit(const std::string& mnemonic) const { *out << "\t" << mnemonic << "\n"; }
void PIC14CodeGen::emit(const std::string& mnemonic, const std::string& op1) const { *out << "\t" << mnemonic << "\t" << op1 << "\n"; }
void PIC14CodeGen::emit(const std::string& mnemonic, const std::string& op1, const std::string& op2) const { *out << "\t" << mnemonic << "\t" << op1 << ", " << op2 << "\n"; }
void PIC14CodeGen::emit_label(const std::string& label) const { *out << label << ":\n"; }
void PIC14CodeGen::emit_comment(const std::string& comment) const { *out << "; " << comment << "\n"; }
void PIC14CodeGen::emit_raw(const std::string& text) const { *out << text << "\n"; }

void PIC14CodeGen::compile(const tacky::Program& program, std::ostream& os) {
    out = &os;

    StackAllocator allocator;
    auto [offsets, total_size] = allocator.allocate(program);
    this->stack_layout = offsets;

    emit_comment("Generated by pymcuc for " + config.chip);
    emit_raw("\tPROCESSOR " + config.chip);
    emit_raw("\t#include <xc.inc>");

    emit_raw("\t__CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _CP_OFF");

    emit_comment("--- Compiled Stack (Overlays) ---");
    emit_raw("\tUDATA_SHR");
    emit_raw(std::format("_stack_base RES {}", total_size));

    emit_raw("");
    emit_comment("--- Variable Offsets ---");
    for (const auto& [name, offset] : stack_layout) {
        emit_raw(std::format("{} EQU _stack_base + {}", name, offset));
    }

    emit_raw("");
    emit_comment("--- Code ---");
    emit_raw("\tORG 0x00");
    emit("GOTO", "main");
    emit_raw("\tORG 0x04");
    emit("RETFIE");

    for (const auto& func : program.functions) {
        compile_function(func);
    }
    emit_raw("\tEND");
}

void PIC14CodeGen::compile_function(const tacky::Function& func) {
    emit_label(func.name);
    current_bank = -1;
    for (const auto& instr : func.body) {
        compile_instruction(instr);
    }
}

void PIC14CodeGen::compile_instruction(const tacky::Instruction& instr) {
    std::visit([this](auto&& arg) { compile_variant(arg); }, instr);
}

void PIC14CodeGen::load_into_w(const tacky::Val& val) {
    if (const auto c = std::get_if<tacky::Constant>(&val)) {
        emit("MOVLW", std::format("0x{:02X}", c->value & 0xFF));
    } else {
        std::string op = resolve_address(val);
        select_bank(op);
        emit("MOVF", op, "W");
    }
}

void PIC14CodeGen::store_w_into(const tacky::Val& val) {
    std::string op = resolve_address(val);
    select_bank(op);
    emit("MOVWF", op);
}

void PIC14CodeGen::compile_variant(const tacky::Return& arg) {
    load_into_w(arg.value);
    emit("RETURN");
}

void PIC14CodeGen::compile_variant(const tacky::Copy& arg) {
    load_into_w(arg.src);
    store_w_into(arg.dst);
}

void PIC14CodeGen::compile_variant(const tacky::Unary& arg) {
    load_into_w(arg.src);
    switch (arg.op) {
        case tacky::UnaryOp::BitNot: emit("XORLW", "0xFF"); break;
        case tacky::UnaryOp::Not:    emit("XORLW", "1"); emit("ANDLW", "1"); break;
        case tacky::UnaryOp::Neg:    emit("SUBLW", "0"); break;
    }
    store_w_into(arg.dst);
}

void PIC14CodeGen::compile_variant(const tacky::Binary& arg) {
    bool is_comparison = false;
    switch(arg.op) {
        case tacky::BinaryOp::Equal: case tacky::BinaryOp::NotEqual:
        case tacky::BinaryOp::LessThan: case tacky::BinaryOp::LessEqual:
        case tacky::BinaryOp::GreaterThan: case tacky::BinaryOp::GreaterEqual:
            is_comparison = true; break;
        default: break;
    }

    if (!is_comparison) {
        load_into_w(arg.src2);
        std::string addr1 = resolve_address(arg.src1);
        select_bank(addr1);

        switch(arg.op) {
            case tacky::BinaryOp::Add: emit("ADDWF", addr1, "W"); break;
            case tacky::BinaryOp::Sub:
                emit("SUBWF", addr1, "W"); break;
            case tacky::BinaryOp::BitAnd: emit("ANDWF", addr1, "W"); break;
            case tacky::BinaryOp::BitOr:  emit("IORWF", addr1, "W"); break;
            case tacky::BinaryOp::BitXor: emit("XORWF", addr1, "W"); break;
            default: break;
        }
        store_w_into(arg.dst);
        return;
    }

    load_into_w(arg.src2);

    std::string addr1 = resolve_address(arg.src1);
    select_bank(addr1);
    emit("SUBWF", addr1, "W");

    std::string dst_addr = resolve_address(arg.dst);
    select_bank(dst_addr);
    emit("CLRF", dst_addr);

    switch(arg.op) {
        case tacky::BinaryOp::Equal:      emit("BTFSC", "STATUS, 2"); break;
        case tacky::BinaryOp::NotEqual:   emit("BTFSS", "STATUS, 2"); break;
        case tacky::BinaryOp::LessThan:   emit("BTFSS", "STATUS, 0"); break;
        case tacky::BinaryOp::GreaterEqual: emit("BTFSC", "STATUS, 0"); break;
        case tacky::BinaryOp::GreaterThan: emit("BTFSC", "STATUS, 0"); break;
        case tacky::BinaryOp::LessEqual:  emit("BTFSS", "STATUS, 0"); break;
        default: break;
    }
    emit("INCF", dst_addr, "F");
}

void PIC14CodeGen::compile_variant(const tacky::BitSet& arg) {
    std::string addr = resolve_address(arg.target);
    select_bank(addr);
    emit("BSF", addr, std::to_string(arg.bit));
}

void PIC14CodeGen::compile_variant(const tacky::BitClear& arg) {
    std::string addr = resolve_address(arg.target);
    select_bank(addr);
    emit("BCF", addr, std::to_string(arg.bit));
}

void PIC14CodeGen::compile_variant(const tacky::BitCheck& arg) {
    std::string addr = resolve_address(arg.source);
    select_bank(addr);

    std::string dst_addr = resolve_address(arg.dst);
    {
        select_bank(dst_addr);
        emit("CLRF", dst_addr);

        emit("BTFSC", addr, std::to_string(arg.bit));

        select_bank(dst_addr);
        emit("INCF", dst_addr, "F");
    }
}

void PIC14CodeGen::compile_variant(const tacky::BitWrite& arg) {
    load_into_w(arg.src);
    emit("IORLW", "0");

    std::string addr = resolve_address(arg.target);
    std::string bit_str = std::to_string(arg.bit);
    std::string lbl_zero = make_label("L_BZ");
    std::string lbl_end = make_label("L_BE");

    emit("BTFSC", "STATUS, 2"); // Skip if not zero
    emit("GOTO", lbl_zero);

    select_bank(addr);
    emit("BSF", addr, bit_str);
    emit("GOTO", lbl_end);

    emit_label(lbl_zero);
    select_bank(addr);
    emit("BCF", addr, bit_str);

    emit_label(lbl_end);
}

void PIC14CodeGen::compile_variant(const tacky::Label& arg) const { emit_label(arg.name); }
void PIC14CodeGen::compile_variant(const tacky::Jump& arg) const { emit("GOTO", arg.target); }

void PIC14CodeGen::compile_variant(const tacky::JumpIfZero& arg) {
    load_into_w(arg.condition);
    emit("IORLW", "0");
    emit("BTFSC", "STATUS, 2");
    emit("GOTO", arg.target);
}

void PIC14CodeGen::compile_variant(const tacky::JumpIfNotZero& arg) {
    load_into_w(arg.condition);
    emit("IORLW", "0");
    emit("BTFSS", "STATUS, 2");
    emit("GOTO", arg.target);
}

void PIC14CodeGen::compile_variant(const tacky::Call& arg) {
    emit("CALL", arg.function_name);
    if (!std::holds_alternative<tacky::Variable>(arg.dst) &&
        !std::holds_alternative<tacky::Temporary>(arg.dst)) {
    } else {
        store_w_into(arg.dst);
    }
}