#include "PIC14CodeGen.h"
#include <format>
#include <utility>
#include <variant>
#include <iostream>

PIC14CodeGen::PIC14CodeGen(DeviceConfig  cfg) : config(std::move(cfg)), out(nullptr) {
    if (config.chip == "pic16f877a") {
        ram_head = 0x20;
    } else {
        ram_head = 0x0C;
    }
}

int PIC14CodeGen::resolve_address(const tacky::Val& val) {
    if (const auto c = std::get_if<tacky::Constant>(&val)) return c->value;
    if (const auto mem = std::get_if<tacky::MemoryAddress>(&val)) return mem->address;

    std::string name;
    if (const auto v = std::get_if<tacky::Variable>(&val)) name = v->name;
    else if (const auto t = std::get_if<tacky::Temporary>(&val)) name = t->name;

    return get_or_alloc_variable(name);
}

int PIC14CodeGen::get_or_alloc_variable(const std::string& name) {
    if (!symbol_table.contains(name)) {
        symbol_table[name] = ram_head++;
        emit_raw(std::format("{} EQU 0x{:02X}", name, symbol_table[name]));
    }
    return symbol_table[name];
}

void PIC14CodeGen::select_bank(const int address) {
    const int new_bank = (address >> 7) & 0x03;

    if (current_bank == new_bank) return;

    if (new_bank & 1) emit("BSF", "3, 5"); else emit("BCF", "3, 5"); // RP0
    if (new_bank & 2) emit("BSF", "3, 6"); else emit("BCF", "3, 6"); // RP1

    current_bank = new_bank;
}

void PIC14CodeGen::emit(const std::string& mnemonic) const {
    *out << "\t" << mnemonic << "\n";
}
void PIC14CodeGen::emit(const std::string& mnemonic, const std::string& op1) const {
    *out << "\t" << mnemonic << "\t" << op1 << "\n";
}
void PIC14CodeGen::emit(const std::string& mnemonic, const std::string& op1, const std::string& op2) const {
    *out << "\t" << mnemonic << "\t" << op1 << ", " << op2 << "\n";
}
void PIC14CodeGen::emit_label(const std::string& label) const {
    *out << label << ":\n";
}
void PIC14CodeGen::emit_comment(const std::string& comment) const {
    *out << "; " << comment << "\n";
}
void PIC14CodeGen::emit_raw(const std::string& text) const {
    *out << text << "\n";
}

void PIC14CodeGen::compile(const tacky::Program& program, std::ostream& os) {
    out = &os;

    emit_comment("Generated by pymcuc for " + config.chip);
    emit_raw("\tPROCESSOR " + config.chip);
    emit_raw("\t#include <xc.inc>");

    if (!config.fuses.empty()) {
        std::string cfg = "\t__CONFIG ";
        bool first = true;
        for (const auto& [k, v] : config.fuses) {
            if (!first) cfg += " & ";
            cfg += "_" + k + "_" + v;
            first = false;
        }
        emit_raw(cfg);
    } else {
        emit_raw("\t__CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _CP_OFF");
    }

    emit_comment("--- Variables ---");
    emit_raw("\tUDATA_SHR");

    emit_raw("");
    emit_comment("--- Code ---");
    emit_raw("\tORG 0x00");
    emit("GOTO", "main");
    emit_raw("\tORG 0x04");
    emit("RETFIE");

    for (const auto& func : program.functions) {
        compile_function(func);
    }

    emit_raw("\tEND");
}

void PIC14CodeGen::compile_function(const tacky::Function& func) {
    emit_label(func.name);
    current_bank = -1;

    for (const auto& instr : func.body) {
        compile_instruction(instr);
    }
}

void PIC14CodeGen::compile_instruction(const tacky::Instruction& instr) {
    std::visit([this](auto&& arg) { compile_variant(arg); }, instr);
}

void PIC14CodeGen::load_into_w(const tacky::Val& val) {
    if (const auto c = std::get_if<tacky::Constant>(&val)) {
        emit("MOVLW", std::format("0x{:02X}", c->value & 0xFF));
    } else {
        int addr = resolve_address(val);
        select_bank(addr);
        emit("MOVF", std::format("0x{:02X}", addr), "W");
    }
}

void PIC14CodeGen::store_w_into(const tacky::Val& val) {
    int addr = resolve_address(val);
    select_bank(addr);
    emit("MOVWF", std::format("0x{:02X}", addr));
}


void PIC14CodeGen::compile_variant(const tacky::Return& arg) {
    load_into_w(arg.value);
    emit("RETURN");
}

void PIC14CodeGen::compile_variant(const tacky::Copy& arg) {
    load_into_w(arg.src);
    store_w_into(arg.dst);
}

void PIC14CodeGen::compile_variant(const tacky::Unary& arg) {
    load_into_w(arg.src);

    switch (arg.op) {
        case tacky::UnaryOp::BitNot:
        case tacky::UnaryOp::Not:
            emit("XORLW", "0xFF");
            break;
        case tacky::UnaryOp::Neg:
            emit("SUBLW", "0"); // 0 - W = -W
            break;
    }
    store_w_into(arg.dst);
}

void PIC14CodeGen::compile_variant(const tacky::Binary& arg) {
    load_into_w(arg.src1);

    if (const auto c = std::get_if<tacky::Constant>(&arg.src2)) {
        const std::string val = std::format("0x{:02X}", c->value & 0xFF);
        switch(arg.op) {
            case tacky::BinaryOp::Add: emit("ADDLW", val); break;
            case tacky::BinaryOp::Sub: emit("SUBLW", val); break;
            case tacky::BinaryOp::BitAnd: emit("ANDLW", val); break;
            case tacky::BinaryOp::BitOr:  emit("IORLW", val); break;
            case tacky::BinaryOp::BitXor: emit("XORLW", val); break;
            default: emit_comment("TODO: Complex binary op with constant");
        }
    } else {
        int addr = resolve_address(arg.src2);
        select_bank(addr);
        const std::string addr_str = std::format("0x{:02X}", addr);

        switch(arg.op) {
            case tacky::BinaryOp::Add: emit("ADDWF", addr_str, "W"); break;
            case tacky::BinaryOp::Sub: emit("SUBWF", addr_str, "W"); break; // f - W
            case tacky::BinaryOp::BitAnd: emit("ANDWF", addr_str, "W"); break;
            case tacky::BinaryOp::BitOr:  emit("IORWF", addr_str, "W"); break;
            case tacky::BinaryOp::BitXor: emit("XORWF", addr_str, "W"); break;
            default: emit_comment("TODO: Complex binary op with var");
        }
    }
    store_w_into(arg.dst);
}

void PIC14CodeGen::compile_variant(const tacky::BitSet& arg) {
    int addr = resolve_address(arg.target);
    select_bank(addr);
    emit("BSF", std::format("0x{:02X}", addr), std::to_string(arg.bit));
}

void PIC14CodeGen::compile_variant(const tacky::BitClear& arg) {
    int addr = resolve_address(arg.target);
    select_bank(addr);
    emit("BCF", std::format("0x{:02X}", addr), std::to_string(arg.bit));
}

void PIC14CodeGen::compile_variant(const tacky::BitCheck& arg) {
    int addr = resolve_address(arg.source);
    select_bank(addr);

    int dst_addr = resolve_address(arg.dst);
    select_bank(dst_addr);
    emit("CLRF", std::format("0x{:02X}", dst_addr));

    select_bank(addr);
    emit("BTFSC", std::format("0x{:02X}", addr), std::to_string(arg.bit));

    select_bank(dst_addr);
    emit("INCF", std::format("0x{:02X}", dst_addr), "F");
}

void PIC14CodeGen::compile_variant(const tacky::Label& arg) const {
    emit_label(arg.name);
}
void PIC14CodeGen::compile_variant(const tacky::Jump& arg) const {
    emit("GOTO", arg.target);
}

void PIC14CodeGen::compile_variant(const tacky::JumpIfZero& arg) {
    load_into_w(arg.condition);
    emit("BTFSC", "3, 2");
    emit("GOTO", arg.target);
}

void PIC14CodeGen::compile_variant(const tacky::JumpIfNotZero& arg) {
    load_into_w(arg.condition);
    emit("BTFSS", "3, 2");
    emit("GOTO", arg.target);
}

void PIC14CodeGen::compile_variant(const tacky::Call& arg) {
    emit("CALL", arg.function_name);

    if (!std::holds_alternative<tacky::Variable>(arg.dst) &&
        !std::holds_alternative<tacky::Temporary>(arg.dst)) {
    } else {
        store_w_into(arg.dst);
    }
}