#include "PIC14CodeGen.h"
#include <format>
#include <variant>
#include <ostream>

void PIC14CodeGen::compile(const tacky::Program& program, std::ostream& os) {
    out = &os;

    // 1. Standard Header for GPASM
    *out << "; Generated by pymcuc (PIC14 Backend)\n";
    *out << "\tPROCESSOR 16F84A\n";
    *out << "\t#include <xc.inc>\n\n"; // Or p16f84a.inc if pure gputils is used

    *out << "\t__CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _CP_OFF\n\n";

    // 2. Data Section
    *out << "; --- Data Section ---\n";
    *out << "\tUDATA\n"; // Start of uninitialized memory
    // Here we could pre-declare variables, but GPASM allows 'RES 1' inline
    // if we use cblock, but UDATA is more modern for linkers.
    // For simplicity in this step, we'll use direct address EQU definitions on the fly.

    *out << "\n; --- Code Section ---\n";
    *out << "\tCODE\n";
    *out << "\tORG 0x00\n";
    *out << "\tGOTO main\n\n"; // Reset vector

    // 3. Compile functions
    for (const auto& func : program.functions) {
        compile_function(func);
    }

    *out << "\tEND\n";
}

// --- Memory Management ---

int PIC14CodeGen::get_or_alloc_variable(const std::string& name) {
    if (symbol_table.find(name) == symbol_table.end()) {
        symbol_table[name] = ram_head++;
        // Emit EQU definition for debug and clarity in the ASM
        // Note: In a real compiler, this would go in a CBLOCK block
        *out << name << " EQU 0x" << std::hex << symbol_table[name] << std::dec << "\n";
    }
    return symbol_table[name];
}

// --- Helpers ---

void PIC14CodeGen::emit(const std::string& instr) {
    *out << "\t" << instr << "\n";
}

void PIC14CodeGen::emit(const std::string& instr, const std::string& operand) {
    *out << "\t" << instr << "\t" << operand << "\n";
}

void PIC14CodeGen::emit_label(const std::string& label) {
    *out << label << ":\n";
}

// --- Data and Stack Management ---

void PIC14CodeGen::load_into_w(const tacky::Val& val) {
    if (std::holds_alternative<tacky::Constant>(val)) {
        int const_val = std::get<tacky::Constant>(val).value;
        emit("MOVLW", std::format("0x{:02X}", const_val & 0xFF));
    }
    else if (std::holds_alternative<tacky::Variable>(val)) {
        std::string name = std::get<tacky::Variable>(val).name;
        emit("MOVF", name + ", W");
    }
    else if (std::holds_alternative<tacky::Temporary>(val)) {
        std::string name = std::get<tacky::Temporary>(val).name;
        // Ensure the temporary exists (should have been written before)
        get_or_alloc_variable(name);
        emit("MOVF", name + ", W");
    }
}

void PIC14CodeGen::store_w_into(const tacky::Val& val) {
    std::string name;

    if (std::holds_alternative<tacky::Variable>(val)) {
        name = std::get<tacky::Variable>(val).name;
    }
    else if (std::holds_alternative<tacky::Temporary>(val)) {
        name = std::get<tacky::Temporary>(val).name;
    }
    else {
        // Attempting to write to a constant is a compiler bug (IRGen error)
        throw std::runtime_error("Internal Error: Cannot store into a Constant");
    }

    // Ensure space in RAM
    get_or_alloc_variable(name);
    emit("MOVWF", name);
}

// --- Function and Instruction Compilation ---

void PIC14CodeGen::compile_function(const tacky::Function& func) {
    emit_label(func.name);

    // Analyze instructions
    for (const auto& instr : func.body) {
        compile_instruction(instr);
    }
}

void PIC14CodeGen::compile_instruction(const tacky::Instruction& instr) {
    // Use std::visit to "unpack" the instruction variant
    std::visit([this](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;

        // 1. Instruction RETURN
        if constexpr (std::is_same_v<T, tacky::Return>) {
            // Load return value into W
            load_into_w(arg.value);
            // Execute return
            emit("RETURN");
        }

        // 2. Instruction UNARY (Not, Neg, etc.)
        else if constexpr (std::is_same_v<T, tacky::Unary>) {
            load_into_w(arg.src);

            if (arg.op == tacky::UnaryOp::Complement) {
                emit("XORLW", "0xFF"); // Bitwise NOT in PIC
            }
            else if (arg.op == tacky::UnaryOp::Neg) {
                // Arithmetic Negation (Two's complement): NOT + 1
                emit("XORLW", "0xFF");
                emit("ADDLW", "1");
            }

            store_w_into(arg.dst);
        }

        // 3. Instruction BINARY (Add, Sub, etc.)
        else if constexpr (std::is_same_v<T, tacky::Binary>) {
            // Strategy: Load src1 into W, operate with src2
            load_into_w(arg.src1);

            // Operations
            // Note: For simplicity, assume src2 is Constant or Variable
            // PIC has different instructions for ADDLW (Literal) vs ADDWF (File)

            bool src2_is_const = std::holds_alternative<tacky::Constant>(arg.src2);
            std::string op_suffix = src2_is_const ? "LW" : "WF";
            std::string operand;

            if (src2_is_const) {
                int val = std::get<tacky::Constant>(arg.src2).value;
                operand = std::format("0x{:02X}", val & 0xFF);
            } else {
                // Is variable or temporary
                if (std::holds_alternative<tacky::Variable>(arg.src2))
                    operand = std::get<tacky::Variable>(arg.src2).name;
                else
                    operand = std::get<tacky::Temporary>(arg.src2).name;

                // If we use WF instruction, the destination is W (W = W + F)
                operand += ", W";
            }

            if (arg.op == tacky::BinaryOp::Add) {
                emit("ADD" + op_suffix, operand);
            }
            else if (arg.op == tacky::BinaryOp::Sub) {
                emit("SUB" + op_suffix, operand);
            }
            // ... implement other ops ...

            store_w_into(arg.dst);
        }

        // 4. Instruction COPY (Assignment)
        else if constexpr (std::is_same_v<T, tacky::Copy>) {
            load_into_w(arg.src);
            store_w_into(arg.dst);
        }

        // 5. Labels and Jumps (For future if/while)
        else if constexpr (std::is_same_v<T, tacky::Label>) {
            emit_label(arg.name);
        }
        else if constexpr (std::is_same_v<T, tacky::Jump>) {
            emit("GOTO", arg.target);
        }

    }, instr);
}