/*
 * -----------------------------------------------------------------------------
 * PyMCU Compiler (pymcuc)
 * Copyright (C) 2026 Ivan Montiel Cardona and the PyMCU Project Authors
 *
 * SPDX-License-Identifier: MIT
 *
 * -----------------------------------------------------------------------------
 * SAFETY WARNING / HIGH RISK ACTIVITIES:
 * THE SOFTWARE IS NOT DESIGNED, MANUFACTURED, OR INTENDED FOR USE IN HAZARDOUS
 * ENVIRONMENTS REQUIRING FAIL-SAFE PERFORMANCE, SUCH AS IN THE OPERATION OF
 * NUCLEAR FACILITIES, AIRCRAFT NAVIGATION OR COMMUNICATION SYSTEMS, AIR
 * TRAFFIC CONTROL, DIRECT LIFE SUPPORT MACHINES, OR WEAPONS SYSTEMS.
 * -----------------------------------------------------------------------------
 */

using PyMCU.Backend.Analysis;
using PyMCU.Common;
using PyMCU.Common.Models;
using PyMCU.IR;

namespace PyMCU.Backend.Targets.RiscV;

public class RiscvCodeGen(DeviceConfig cfg) : CodeGen
{
    private List<RISCVAsmLine> assembly = new();
    private Dictionary<string, int> stackLayout = new();
    private int currentStackAdjustment;
    private string currentFuncName = "";
    private bool currentIsLeaf;
    private int labelCounter;

    public override void EmitContextSave() { }
    public override void EmitContextRestore() { }
    public override void EmitInterruptReturn() { }

    private string MakeLabel(string prefix) => $"{prefix}_{labelCounter++}";

    private void Emit(string m) => assembly.Add(RISCVAsmLine.MakeInstruction(m));
    private void Emit(string m, string o1) => assembly.Add(RISCVAsmLine.MakeInstruction(m, o1));
    private void Emit(string m, string o1, string o2) => assembly.Add(RISCVAsmLine.MakeInstruction(m, o1, o2));
    private void Emit(string m, string o1, string o2, string o3) => assembly.Add(RISCVAsmLine.MakeInstruction(m, o1, o2, o3));
    private void EmitLabel(string l) => assembly.Add(RISCVAsmLine.MakeLabel(l));
    private void EmitComment(string c) => assembly.Add(RISCVAsmLine.MakeComment(c));
    private void EmitRaw(string t) => assembly.Add(RISCVAsmLine.MakeRaw(t));

    private void LoadIntoReg(Val val, string reg)
    {
        if (val is Constant c)
        {
            Emit("li", reg, c.Value.ToString());
        }
        else if (val is MemoryAddress mem)
        {
            Emit("li", "t2", $"0x{mem.Address:X8}");
            Emit("lw", reg, "0(t2)");
        }
        else
        {
            string name = val is Variable vr ? vr.Name : val is Temporary tr ? tr.Name : "";
            if (!string.IsNullOrEmpty(name) && stackLayout.TryGetValue(name, out int offset))
                Emit("lw", reg, $"{offset}(s0)");
            else if (!string.IsNullOrEmpty(name))
            {
                Emit("la", "t2", name);
                Emit("lw", reg, "0(t2)");
            }
        }
    }

    private void StoreRegInto(string reg, Val val)
    {
        if (val is Constant) return;

        if (val is MemoryAddress mem)
        {
            Emit("li", "t2", $"0x{mem.Address:X8}");
            Emit("sw", reg, "0(t2)");
        }
        else
        {
            string name = val is Variable vr ? vr.Name : val is Temporary tr ? tr.Name : "";
            if (!string.IsNullOrEmpty(name) && stackLayout.TryGetValue(name, out int offset))
                Emit("sw", reg, $"{offset}(s0)");
            else if (!string.IsNullOrEmpty(name))
            {
                Emit("la", "t2", name);
                Emit("sw", reg, "0(t2)");
            }
        }
    }

    public override void Compile(ProgramIR program, TextWriter output)
    {
        assembly.Clear();
        EmitComment($"Generated by pymcuc for RISC-V ({cfg.Chip})");
        EmitRaw(".attribute arch, \"rv32ec\"");
        EmitRaw(".attribute unaligned_access, 0");
        EmitRaw(".attribute stack_align, 16");
        EmitRaw(".section .text");
        EmitRaw(".align 2");

        foreach (var func in program.Functions)
            CompileFunction(func);

        var optimized = RiscvPeephole.Optimize(assembly);
        foreach (var line in optimized)
            output.WriteLine(line.ToString());
    }

    private void CompileFunction(Function func)
    {
        currentFuncName = func.Name;
        currentIsLeaf = true;

        foreach (var instr in func.Body)
        {
            if (instr is Call) { currentIsLeaf = false; break; }
            if (instr is Binary bin && (bin.Op == PyMCU.IR.BinaryOp.Mul || bin.Op == PyMCU.IR.BinaryOp.Div ||
                bin.Op == PyMCU.IR.BinaryOp.FloorDiv || bin.Op == PyMCU.IR.BinaryOp.Mod))
            {
                currentIsLeaf = false;
                break;
            }
        }

        var allocator = new DynamicStackAllocator();
        var (offsets, frameSize) = allocator.Allocate(func);
        stackLayout = offsets;
        currentStackAdjustment = frameSize;

        EmitRaw(".globl " + func.Name);
        EmitLabel(func.Name);

        if (func.Name == "main")
            Emit("li", "sp", "0x20000800");

        // Prologue
        Emit("addi", "sp", "sp", (-currentStackAdjustment).ToString());
        if (!currentIsLeaf)
            Emit("sw", "ra", $"{currentStackAdjustment - 4}(sp)");
        Emit("sw", "s0", $"{currentStackAdjustment - 8}(sp)");
        Emit("addi", "s0", "sp", currentStackAdjustment.ToString());

        foreach (var instr in func.Body)
            CompileInstruction(instr);
    }

    private void CompileInstruction(Instruction instr)
    {
        switch (instr)
        {
            case Copy arg: CompileCopy(arg); break;
            case Return arg: CompileReturn(arg); break;
            case Jump arg: Emit("j", arg.Target); break;
            case JumpIfZero arg: LoadIntoReg(arg.Condition, "t0"); Emit("beqz", "t0", arg.Target); break;
            case JumpIfNotZero arg: LoadIntoReg(arg.Condition, "t0"); Emit("bnez", "t0", arg.Target); break;
            case JumpIfEqual arg: LoadIntoReg(arg.Src1, "t0"); LoadIntoReg(arg.Src2, "t1"); Emit("beq", "t0", "t1", arg.Target); break;
            case JumpIfNotEqual arg: LoadIntoReg(arg.Src1, "t0"); LoadIntoReg(arg.Src2, "t1"); Emit("bne", "t0", "t1", arg.Target); break;
            case JumpIfLessThan arg: LoadIntoReg(arg.Src1, "t0"); LoadIntoReg(arg.Src2, "t1"); Emit("blt", "t0", "t1", arg.Target); break;
            case JumpIfLessOrEqual arg: LoadIntoReg(arg.Src1, "t0"); LoadIntoReg(arg.Src2, "t1"); Emit("ble", "t0", "t1", arg.Target); break;
            case JumpIfGreaterThan arg: LoadIntoReg(arg.Src1, "t0"); LoadIntoReg(arg.Src2, "t1"); Emit("bgt", "t0", "t1", arg.Target); break;
            case JumpIfGreaterOrEqual arg: LoadIntoReg(arg.Src1, "t0"); LoadIntoReg(arg.Src2, "t1"); Emit("bge", "t0", "t1", arg.Target); break;
            case Label arg: EmitLabel(arg.Name); break;
            case Call arg: Emit("call", arg.FunctionName); StoreRegInto("a0", arg.Dst); break;
            case Unary arg: CompileUnary(arg); break;
            case Binary arg: CompileBinary(arg); break;
            case BitSet arg: CompileBitSet(arg); break;
            case BitClear arg: CompileBitClear(arg); break;
            case BitCheck arg: CompileBitCheck(arg); break;
            case BitWrite arg: CompileBitWrite(arg); break;
            case JumpIfBitSet arg: LoadIntoReg(arg.Source, "t0"); Emit("srli", "t0", "t0", arg.Bit.ToString()); Emit("andi", "t0", "t0", "1"); Emit("bnez", "t0", arg.Target); break;
            case JumpIfBitClear arg: LoadIntoReg(arg.Source, "t0"); Emit("srli", "t0", "t0", arg.Bit.ToString()); Emit("andi", "t0", "t0", "1"); Emit("beqz", "t0", arg.Target); break;
            case AugAssign: throw new NotSupportedException("RISC-V: AugAssign is not yet implemented");
            case LoadIndirect: throw new NotSupportedException("RISC-V: LoadIndirect is not yet implemented");
            case StoreIndirect: throw new NotSupportedException("RISC-V: StoreIndirect is not yet implemented");
            case InlineAsm arg: assembly.Add(RISCVAsmLine.MakeRaw(arg.Code)); break;
            case DebugLine arg:
                if (!string.IsNullOrEmpty(arg.SourceFile)) EmitComment($"{arg.SourceFile}:{arg.Line}: {arg.Text}");
                else EmitComment($"Line {arg.Line}: {arg.Text}");
                break;
            case UARTSendString: break;
            case ArrayLoad: break;
            case ArrayStore: break;
        }
    }

    private void CompileReturn(Return arg)
    {
        if (arg.Value is not NoneVal)
            LoadIntoReg(arg.Value, "a0");

        if (currentFuncName == "main")
        {
            string endLabel = MakeLabel("end_loop");
            EmitLabel(endLabel);
            Emit("j", endLabel);
        }
        else
        {
            if (!currentIsLeaf)
                Emit("lw", "ra", $"{currentStackAdjustment - 4}(sp)");
            Emit("lw", "s0", $"{currentStackAdjustment - 8}(sp)");
            Emit("addi", "sp", "sp", currentStackAdjustment.ToString());
            Emit("ret");
        }
    }

    private void CompileCopy(Copy arg)
    {
        LoadIntoReg(arg.Src, "t0");
        StoreRegInto("t0", arg.Dst);
    }

    private void CompileUnary(Unary arg)
    {
        LoadIntoReg(arg.Src, "t0");
        switch (arg.Op)
        {
            case PyMCU.IR.UnaryOp.Neg: Emit("neg", "t0", "t0"); break;
            case PyMCU.IR.UnaryOp.BitNot: Emit("not", "t0", "t0"); break;
            case PyMCU.IR.UnaryOp.Not: Emit("seqz", "t0", "t0"); break;
        }
        StoreRegInto("t0", arg.Dst);
    }

    private void CompileBinary(Binary arg)
    {
        LoadIntoReg(arg.Src1, "t0");

        bool usedImmediate = false;
        if (arg.Src2 is Constant c2 && c2.Value >= -2048 && c2.Value <= 2047)
        {
            int val = c2.Value;
            switch (arg.Op)
            {
                case PyMCU.IR.BinaryOp.Add: Emit("addi", "t0", "t0", val.ToString()); usedImmediate = true; break;
                case PyMCU.IR.BinaryOp.Sub: Emit("addi", "t0", "t0", (-val).ToString()); usedImmediate = true; break;
                case PyMCU.IR.BinaryOp.BitAnd: Emit("andi", "t0", "t0", val.ToString()); usedImmediate = true; break;
                case PyMCU.IR.BinaryOp.BitOr: Emit("ori", "t0", "t0", val.ToString()); usedImmediate = true; break;
                case PyMCU.IR.BinaryOp.BitXor: Emit("xori", "t0", "t0", val.ToString()); usedImmediate = true; break;
                case PyMCU.IR.BinaryOp.LessThan: Emit("slti", "t0", "t0", val.ToString()); usedImmediate = true; break;
            }
        }

        if (!usedImmediate)
        {
            LoadIntoReg(arg.Src2, "t1");
            switch (arg.Op)
            {
                case PyMCU.IR.BinaryOp.Add: Emit("add", "t0", "t0", "t1"); break;
                case PyMCU.IR.BinaryOp.Sub: Emit("sub", "t0", "t0", "t1"); break;
                case PyMCU.IR.BinaryOp.BitAnd: Emit("and", "t0", "t0", "t1"); break;
                case PyMCU.IR.BinaryOp.BitOr: Emit("or", "t0", "t0", "t1"); break;
                case PyMCU.IR.BinaryOp.BitXor: Emit("xor", "t0", "t0", "t1"); break;
                case PyMCU.IR.BinaryOp.Mul:
                    Emit("mv", "a0", "t0"); Emit("mv", "a1", "t1");
                    Emit("call", "__mulsi3"); Emit("mv", "t0", "a0");
                    break;
                case PyMCU.IR.BinaryOp.Div:
                case PyMCU.IR.BinaryOp.FloorDiv:
                    Emit("mv", "a0", "t0"); Emit("mv", "a1", "t1");
                    Emit("call", "__divsi3"); Emit("mv", "t0", "a0");
                    break;
                case PyMCU.IR.BinaryOp.Mod:
                    Emit("mv", "a0", "t0"); Emit("mv", "a1", "t1");
                    Emit("call", "__modsi3"); Emit("mv", "t0", "a0");
                    break;
                case PyMCU.IR.BinaryOp.Equal: Emit("xor", "t0", "t0", "t1"); Emit("seqz", "t0", "t0"); break;
                case PyMCU.IR.BinaryOp.NotEqual: Emit("xor", "t0", "t0", "t1"); Emit("snez", "t0", "t0"); break;
                case PyMCU.IR.BinaryOp.LessThan: Emit("slt", "t0", "t0", "t1"); break;
                case PyMCU.IR.BinaryOp.GreaterEqual: Emit("slt", "t0", "t0", "t1"); Emit("seqz", "t0", "t0"); break;
                case PyMCU.IR.BinaryOp.GreaterThan: Emit("slt", "t0", "t1", "t0"); break;
                case PyMCU.IR.BinaryOp.LessEqual: Emit("slt", "t0", "t1", "t0"); Emit("seqz", "t0", "t0"); break;
                case PyMCU.IR.BinaryOp.LShift: Emit("sll", "t0", "t0", "t1"); break;
                case PyMCU.IR.BinaryOp.RShift: Emit("srl", "t0", "t0", "t1"); break;
            }
        }

        StoreRegInto("t0", arg.Dst);
    }

    private void CompileBitSet(BitSet arg)
    {
        LoadIntoReg(arg.Target, "t0");
        Emit("li", "t1", (1 << arg.Bit).ToString());
        Emit("or", "t0", "t0", "t1");
        StoreRegInto("t0", arg.Target);
    }

    private void CompileBitClear(BitClear arg)
    {
        LoadIntoReg(arg.Target, "t0");
        Emit("li", "t1", (~(1 << arg.Bit)).ToString());
        Emit("and", "t0", "t0", "t1");
        StoreRegInto("t0", arg.Target);
    }

    private void CompileBitCheck(BitCheck arg)
    {
        LoadIntoReg(arg.Source, "t0");
        Emit("srli", "t0", "t0", arg.Bit.ToString());
        Emit("andi", "t0", "t0", "1");
        StoreRegInto("t0", arg.Dst);
    }

    private void CompileBitWrite(BitWrite arg)
    {
        LoadIntoReg(arg.Src, "t0");
        LoadIntoReg(arg.Target, "t1");
        Emit("li", "t2", (~(1 << arg.Bit)).ToString());
        Emit("and", "t1", "t1", "t2");
        Emit("snez", "t0", "t0");
        Emit("slli", "t0", "t0", arg.Bit.ToString());
        Emit("or", "t1", "t1", "t0");
        StoreRegInto("t1", arg.Target);
    }
}
