"""Write docs/library/hal-parity.md from the AST parity scan."""

from pathlib import Path

from hal_parity import (
    ARCH_COLUMNS,
    REPO,
    api_violations,
    allowlist,
    matrix,
    universality_violations,
)


OUT = REPO / "docs" / "library" / "hal-parity.md"


def _status(symbol: str) -> str:
    item = allowlist().get(symbol)
    if item:
        return item.status
    for allowed, value in allowlist().items():
        if allowed.endswith("*") and symbol.startswith(allowed[:-1]):
            return value.status
    return "untracked"


def main() -> None:
    lines = [
        "# HAL Parity",
        "",
        "Generated by `python3 tests/stdlib/report_hal_parity.py`.",
        "",
        "The scan parses `lib/src/pymcu/hal` and the compatibility repositories with `ast`;",
        "it does not import HAL modules.",
        "",
        "## Backend Matrix",
        "",
        "| Peripheral | " + " | ".join(ARCH_COLUMNS) + " |",
        "|---|" + "|".join("---" for _ in ARCH_COLUMNS) + "|",
    ]
    for peripheral, row in matrix().items():
        lines.append("| " + peripheral + " | " + " | ".join(row[c] for c in ARCH_COLUMNS) + " |")

    api = api_violations()
    universal = universality_violations()
    lines.extend([
        "",
        "## API Deviations",
        "",
        f"{len(api)} facade/API parity deviations are currently allowlisted.",
        "",
    ])
    for violation in api[:80]:
        lines.append(f"- `{violation.symbol}` ({_status(violation.symbol)}): {violation.detail}")
    if len(api) > 80:
        lines.append(f"- ... {len(api) - 80} more")

    lines.extend([
        "",
        "## Compatibility Universality",
        "",
        f"{len(universal)} compatibility-layer file/line violations are currently tracked.",
        "",
    ])
    for violation in universal[:120]:
        lines.append(
            f"- `{violation.layer}:{violation.path}:{violation.line}` "
            f"({ _status(violation.symbol) }): {', '.join(violation.kinds)}"
        )
    if len(universal) > 120:
        lines.append(f"- ... {len(universal) - 120} more")

    OUT.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
