#include "PIOCodeGen.h"
#include <algorithm>
#include <format>
#include <iostream>
#include <set>
#include <variant>

PIOCodeGen::PIOCodeGen(DeviceConfig cfg) : config(std::move(cfg)) {}

void PIOCodeGen::emit(const std::string &mnemonic) const {
  const_cast<PIOCodeGen *>(this)->assembly.push_back(
      PIOAsmLine::Instruction(mnemonic));
}

void PIOCodeGen::emit(const std::string &mnemonic,
                      const std::string &op1) const {
  const_cast<PIOCodeGen *>(this)->assembly.push_back(
      PIOAsmLine::Instruction(mnemonic, op1));
}

void PIOCodeGen::emit(const std::string &mnemonic, const std::string &op1,
                      const std::string &op2) const {
  const_cast<PIOCodeGen *>(this)->assembly.push_back(
      PIOAsmLine::Instruction(mnemonic, op1, op2));
}

void PIOCodeGen::emit(const std::string &mnemonic, const std::string &op1,
                      const std::string &op2, const std::string &op3) const {
  const_cast<PIOCodeGen *>(this)->assembly.push_back(
      PIOAsmLine::Instruction(mnemonic, op1, op2, op3));
}

void PIOCodeGen::emit_label(const std::string &label) const {
  const_cast<PIOCodeGen *>(this)->assembly.push_back(PIOAsmLine::Label(label));
}

void PIOCodeGen::emit_comment(const std::string &comment) const {
  const_cast<PIOCodeGen *>(this)->assembly.push_back(
      PIOAsmLine::Comment(comment));
}

void PIOCodeGen::emit_raw(const std::string &text) const {
  const_cast<PIOCodeGen *>(this)->assembly.push_back(PIOAsmLine::Raw(text));
}

void PIOCodeGen::allocate_registers(const tacky::Function &func) {
  register_map.clear();
  std::set<std::string> vars;

  for (const auto &instr : func.body) {
    auto gather = [&](const tacky::Val &v) {
      if (auto var = std::get_if<tacky::Variable>(&v))
        vars.insert(var->name);
      if (auto tmp = std::get_if<tacky::Temporary>(&v))
        vars.insert(tmp->name);
    };
    std::visit(
        [&](auto &&arg) {
          using T = std::decay_t<decltype(arg)>;
          if constexpr (std::is_same_v<T, tacky::Copy>) {
            gather(arg.src);
            gather(arg.dst);
          } else if constexpr (std::is_same_v<T, tacky::Unary>) {
            gather(arg.src);
            gather(arg.dst);
          } else if constexpr (std::is_same_v<T, tacky::Binary>) {
            gather(arg.src1);
            gather(arg.src2);
            gather(arg.dst);
          } else if constexpr (std::is_same_v<T, tacky::BitSet>) {
            gather(arg.target);
          } else if constexpr (std::is_same_v<T, tacky::BitClear>) {
            gather(arg.target);
          } else if constexpr (std::is_same_v<T, tacky::BitCheck>) {
            gather(arg.source);
            gather(arg.dst);
          } else if constexpr (std::is_same_v<T, tacky::BitWrite>) {
            gather(arg.src);
            gather(arg.target);
          } else if constexpr (std::is_same_v<T, tacky::Return>) {
            gather(arg.value);
          } else if constexpr (std::is_same_v<T, tacky::JumpIfZero>) {
            gather(arg.condition);
          } else if constexpr (std::is_same_v<T, tacky::JumpIfNotZero>) {
            gather(arg.condition);
          } else if constexpr (std::is_same_v<T, tacky::JumpIfBitSet>) {
            gather(arg.source);
          } else if constexpr (std::is_same_v<T, tacky::JumpIfBitClear>) {
            gather(arg.source);
          } else if constexpr (std::is_same_v<T, tacky::Call>) {
            for (const auto &a : arg.args)
              gather(a);
            gather(arg.dst);
          }
        },
        instr);
  }

  int i = 0;
  for (const auto &name : vars) {
    if (i == 0)
      register_map[name] = "X";
    else if (i == 1)
      register_map[name] = "Y";
    else
      throw std::runtime_error(
          "Error: PIO only supports 2 active variables (mapped to X and Y).");
    i++;
  }
}

std::string PIOCodeGen::resolve_operand(const tacky::Val &val) {
  if (const auto c = std::get_if<tacky::Constant>(&val)) {
    return std::to_string(c->value);
  }
  if (const auto var = std::get_if<tacky::Variable>(&val))
    return register_map[var->name];
  if (const auto tmp = std::get_if<tacky::Temporary>(&val))
    return register_map[tmp->name];
  if (const auto mem = std::get_if<tacky::MemoryAddress>(&val)) {
    switch (mem->address) {
    case 0:
      return "PINS";
    case 1:
      return "PIN";
    case 2:
      return "GPIO";
    case 3:
      return "NULL";
    case 4:
      return "ISR";
    case 5:
      return "OSR";
    default:
      return std::format("0x{:X}", mem->address);
    }
  }
  return "";
}

void PIOCodeGen::compile(const tacky::Program &program, std::ostream &os) {
  assembly.clear();
  emit_comment("Generated by pymcuc for RP2040 PIO");
  emit_raw(".program " + config.chip);

  for (const auto &func : program.functions) {
    compile_function(func);
  }

  auto optimized = PIOPeephole::optimize(assembly);
  for (const auto &line : optimized) {
    os << line.to_string() << "\n";
  }
}

void PIOCodeGen::compile_function(const tacky::Function &func) {
  allocate_registers(func);
  emit_label(func.name);
  for (const auto &instr : func.body) {
    compile_instruction(instr);
  }
}

void PIOCodeGen::compile_instruction(const tacky::Instruction &instr) {
  std::visit([this](auto &&arg) { compile_variant(arg); }, instr);
}

void PIOCodeGen::compile_variant(const tacky::Copy &arg) {
  std::string dst = resolve_operand(arg.dst);
  if (const auto c = std::get_if<tacky::Constant>(&arg.src)) {
    emit("SET", dst, std::to_string(c->value & 0x1F));
  } else {
    std::string src = resolve_operand(arg.src);
    emit("MOV", dst, src);
  }
}

void PIOCodeGen::compile_variant(const tacky::Return &arg) {
  // PIO doesn't really have functions with returns in the same way.
  // We can just end the program or loop.
  // For now, let's just emit nothing or a jump to self if it's the end of main.
}

void PIOCodeGen::compile_variant(const tacky::DebugLine &arg) {
  emit_comment(std::format("Line {}: {}", arg.line, arg.text));
}

void PIOCodeGen::compile_variant(const tacky::Jump &arg) const {
  emit("JMP", arg.target);
}

void PIOCodeGen::compile_variant(const tacky::JumpIfZero &arg) {
  if (const auto c = std::get_if<tacky::Constant>(&arg.condition)) {
    if (c->value == 0)
      emit("JMP", arg.target);
    return;
  }
  std::string reg = resolve_operand(arg.condition);
  // PIO JMP conditions: !X, !Y
  if (reg == "X")
    emit("JMP", "!X", arg.target);
  else if (reg == "Y")
    emit("JMP", "!Y", arg.target);
  else
    throw std::runtime_error("PIO JMP condition must be X or Y");
}

void PIOCodeGen::compile_variant(const tacky::JumpIfNotZero &arg) {
  if (const auto c = std::get_if<tacky::Constant>(&arg.condition)) {
    if (c->value != 0)
      emit("JMP", arg.target);
    return;
  }
  std::string reg = resolve_operand(arg.condition);
  // PIO has X-- and Y-- which jump if NOT zero (and then decrement)
  // If we want to jump if NOT zero WITHOUT decrementing, it's harder.
  // We can jump to a small trampoline.
  std::string skip = make_label("skip_jnz");
  if (reg == "X") {
    emit("JMP", "!X", skip);
    emit("JMP", arg.target);
  } else if (reg == "Y") {
    emit("JMP", "!Y", skip);
    emit("JMP", arg.target);
  }
  emit_label(skip);
}

void PIOCodeGen::compile_variant(const tacky::Label &arg) const {
  emit_label(arg.name);
}

void PIOCodeGen::compile_variant(const tacky::Unary &arg) {
  std::string dst = resolve_operand(arg.dst);
  std::string src = resolve_operand(arg.src);
  if (arg.op == tacky::UnaryOp::BitNot) {
    emit("MOV", dst, "!" + src);
  } else {
    throw std::runtime_error("PIO Unary op not supported");
  }
}

void PIOCodeGen::compile_variant(const tacky::Binary &arg) {
  std::string dst = resolve_operand(arg.dst);
  std::string src1 = resolve_operand(arg.src1);
  std::string src2 = resolve_operand(arg.src2);

  if (arg.op == tacky::BinaryOp::Sub) {
    // PIO only has decrementing via JMP reg--
    if (src1 == dst && src2 == "1") {
      std::string next = make_label("next");
      if (dst == "X")
        emit("JMP", "X--", next);
      else if (dst == "Y")
        emit("JMP", "Y--", next);
      else
        throw std::runtime_error(
            "PIO decrement only works on X or Y registers");
      emit_label(next);
    } else {
      throw std::runtime_error(
          "PIO: subtraction only supported as decrement (x = x - 1)");
    }
  } else {
    throw std::runtime_error(
        "PIO: Arithmetic operations (Add, Mul, Div, BitAnd, etc.) are not "
        "supported by PIO hardware.");
  }
}

void PIOCodeGen::compile_variant(const tacky::BitSet &arg) {
  std::string target = resolve_operand(arg.target);
  // In PIO, SET is a group overwrite, not a single bit modification.
  // We treat the bit index as the value if target is PINS or just emit a
  // warning. The issue description says: "Change the logic to treat
  // tacky::Constant values as the full mask for the pin group, not a single bit
  // index." But BitSet IR has an integer 'bit' field.
  emit("SET", target, std::to_string(1 << arg.bit));
}

void PIOCodeGen::compile_variant(const tacky::BitClear &arg) {
  std::string target = resolve_operand(arg.target);
  // Overwrite the group with 0 (or some mask that clears that bit, but SET is
  // group overwrite)
  emit("SET", target, "0");
}

void PIOCodeGen::compile_variant(const tacky::BitCheck &arg) {
  throw std::runtime_error(
      "PIO: BitCheck is not supported (hardware registers are 32-bit and lack "
      "single-bit test instructions).");
}

void PIOCodeGen::compile_variant(const tacky::BitWrite &arg) {
  throw std::runtime_error(
      "PIO: BitWrite is not supported (hardware registers are 32-bit and lack "
      "single-bit modification instructions).");
}

void PIOCodeGen::compile_variant(const tacky::Call &arg) {
  if (arg.function_name == "__pio_pull") {
    std::string block = "BLOCK";
    if (!arg.args.empty()) {
      if (auto c = std::get_if<tacky::Constant>(&arg.args.at(0))) {
        if (c->value == 0)
          block = "NOBLOCK";
      }
    }
    emit("PULL", block);
  } else if (arg.function_name == "__pio_push") {
    std::string block = "BLOCK";
    if (!arg.args.empty()) {
      if (auto c = std::get_if<tacky::Constant>(&arg.args.at(0))) {
        if (c->value == 0)
          block = "NOBLOCK";
      }
    }
    emit("PUSH", block);
  } else if (arg.function_name == "__pio_out") {
    std::string dest = resolve_operand(arg.args.at(0));
    std::string count = resolve_operand(arg.args.at(1));
    emit("OUT", dest, count);
  } else if (arg.function_name == "__pio_in") {
    std::string src = resolve_operand(arg.args.at(0));
    std::string count = resolve_operand(arg.args.at(1));
    emit("IN", src, count);
  } else if (arg.function_name == "__pio_wait") {
    std::string pol = resolve_operand(arg.args.at(0));
    std::string src = resolve_operand(arg.args.at(1));
    std::string idx = resolve_operand(arg.args.at(2));
    emit("WAIT", pol, src, idx);
  } else if (arg.function_name == "delay") {
    if (!assembly.empty() && assembly.back().type == PIOAsmLine::INSTRUCTION) {
      if (const auto c = std::get_if<tacky::Constant>(&arg.args.at(0))) {
        assembly.back().delay = c->value;
      }
    }
  }
}

void PIOCodeGen::compile_variant(const tacky::JumpIfBitSet &arg) {
  // PIO: Use WAIT or JMP PIN for single-pin polling; general case unsupported
  throw std::runtime_error("PIO: JumpIfBitSet is not supported (use WAIT "
                           "instruction via intrinsics).");
}

void PIOCodeGen::compile_variant(const tacky::JumpIfBitClear &arg) {
  throw std::runtime_error("PIO: JumpIfBitClear is not supported (use WAIT "
                           "instruction via intrinsics).");
}

void PIOCodeGen::compile_variant(const tacky::AugAssign &arg) {
  // TODO: Implement PIO-specific augmented assignment
  throw std::runtime_error("PIO: AugAssign is not yet implemented");
}

void PIOCodeGen::compile_variant(const tacky::Delay &arg) {
  // TODO: Implement PIO-specific delay
  throw std::runtime_error("PIO: Delay is not yet implemented");
}
