using PyMCU.Common;
using PyMCU.IR;

namespace PyMCU.Backend.Targets.PIO;

public class PIOCodeGen : CodeGen
{
    private readonly DeviceConfig config;
    private List<PIOAsmLine> assembly = new();
    private Dictionary<string, string> registerMap = new();
    private int labelCounter;

    public PIOCodeGen(DeviceConfig cfg)
    {
        config = cfg;
    }

    public override void EmitContextSave()
    {
    }

    public override void EmitContextRestore()
    {
    }

    public override void EmitInterruptReturn()
    {
    }

    private string MakeLabel(string prefix) => $"{prefix}_{labelCounter++}";

    private void Emit(string m) => assembly.Add(PIOAsmLine.MakeInstruction(m));
    private void Emit(string m, string o1) => assembly.Add(PIOAsmLine.MakeInstruction(m, o1));
    private void Emit(string m, string o1, string o2) => assembly.Add(PIOAsmLine.MakeInstruction(m, o1, o2));

    private void Emit(string m, string o1, string o2, string o3) =>
        assembly.Add(PIOAsmLine.MakeInstruction(m, o1, o2, o3));

    private void EmitLabel(string l) => assembly.Add(PIOAsmLine.MakeLabel(l));
    private void EmitComment(string c) => assembly.Add(PIOAsmLine.MakeComment(c));
    private void EmitRaw(string t) => assembly.Add(PIOAsmLine.MakeRaw(t));

    private void AllocateRegisters(Function func)
    {
        registerMap.Clear();
        var vars = new HashSet<string>();

        foreach (var instr in func.Body)
        {
            void Gather(Val v)
            {
                if (v is Variable vr) vars.Add(vr.Name);
                else if (v is Temporary tr) vars.Add(tr.Name);
            }

            switch (instr)
            {
                case Copy a:
                    Gather(a.Src);
                    Gather(a.Dst);
                    break;
                case Unary a:
                    Gather(a.Src);
                    Gather(a.Dst);
                    break;
                case Binary a:
                    Gather(a.Src1);
                    Gather(a.Src2);
                    Gather(a.Dst);
                    break;
                case BitSet a: Gather(a.Target); break;
                case BitClear a: Gather(a.Target); break;
                case BitCheck a:
                    Gather(a.Source);
                    Gather(a.Dst);
                    break;
                case BitWrite a:
                    Gather(a.Src);
                    Gather(a.Target);
                    break;
                case Return a: Gather(a.Value); break;
                case JumpIfZero a: Gather(a.Condition); break;
                case JumpIfNotZero a: Gather(a.Condition); break;
                case JumpIfBitSet a: Gather(a.Source); break;
                case JumpIfBitClear a: Gather(a.Source); break;
                case Call a:
                    foreach (var arg in a.Args) Gather(arg);
                    Gather(a.Dst);
                    break;
            }
        }

        int i = 0;
        foreach (var name in vars)
        {
            if (i == 0) registerMap[name] = "X";
            else if (i == 1) registerMap[name] = "Y";
            else throw new InvalidOperationException("PIO only supports 2 active variables (mapped to X and Y).");
            i++;
        }
    }

    private string ResolveOperand(Val val)
    {
        if (val is Constant c) return c.Value.ToString();
        if (val is Variable vr) return registerMap.TryGetValue(vr.Name, out var rm) ? rm : vr.Name;
        if (val is Temporary tr) return registerMap.TryGetValue(tr.Name, out var rm2) ? rm2 : tr.Name;
        if (val is MemoryAddress mem)
        {
            return mem.Address switch
            {
                0 => "PINS",
                1 => "PIN",
                2 => "GPIO",
                3 => "NULL",
                4 => "ISR",
                5 => "OSR",
                _ => $"0x{mem.Address:X}"
            };
        }

        return "";
    }

    public override void Compile(ProgramIR program, TextWriter output)
    {
        assembly.Clear();
        EmitComment("Generated by pymcuc for RP2040 PIO");
        EmitRaw(".program " + config.Chip);

        foreach (var func in program.Functions)
            CompileFunction(func);

        var optimized = PIOPeephole.Optimize(assembly);
        foreach (var line in optimized)
            output.WriteLine(line.ToString());
    }

    private void CompileFunction(Function func)
    {
        AllocateRegisters(func);
        EmitLabel(func.Name);
        foreach (var instr in func.Body)
            CompileInstruction(instr);
    }

    private void CompileInstruction(Instruction instr)
    {
        switch (instr)
        {
            case Copy arg: CompileCopy(arg); break;
            case Return: break; // PIO has no function returns
            case Jump arg: Emit("JMP", arg.Target); break;
            case JumpIfZero arg: CompileJumpIfZero(arg); break;
            case JumpIfNotZero arg: CompileJumpIfNotZero(arg); break;
            case Label arg: EmitLabel(arg.Name); break;
            case Call arg: CompileCall(arg); break;
            case Unary arg: CompileUnary(arg); break;
            case Binary arg: CompileBinary(arg); break;
            case BitSet arg: Emit("SET", ResolveOperand(arg.Target), (1 << arg.Bit).ToString()); break;
            case BitClear arg: Emit("SET", ResolveOperand(arg.Target), "0"); break;
            case BitCheck: throw new NotSupportedException("PIO: BitCheck is not supported");
            case BitWrite: throw new NotSupportedException("PIO: BitWrite is not supported");
            case JumpIfBitSet: throw new NotSupportedException("PIO: JumpIfBitSet is not supported");
            case JumpIfBitClear: throw new NotSupportedException("PIO: JumpIfBitClear is not supported");
            case JumpIfEqual: throw new NotSupportedException("PIO: JumpIfEqual not supported");
            case JumpIfNotEqual: throw new NotSupportedException("PIO: JumpIfNotEqual not supported");
            case JumpIfLessThan: throw new NotSupportedException("PIO: JumpIfLessThan not supported");
            case JumpIfLessOrEqual: throw new NotSupportedException("PIO: JumpIfLessOrEqual not supported");
            case JumpIfGreaterThan: throw new NotSupportedException("PIO: JumpIfGreaterThan not supported");
            case JumpIfGreaterOrEqual: throw new NotSupportedException("PIO: JumpIfGreaterOrEqual not supported");
            case AugAssign: throw new NotSupportedException("PIO: AugAssign is not yet implemented");
            case LoadIndirect: throw new NotSupportedException("PIO: LoadIndirect not yet implemented");
            case StoreIndirect: throw new NotSupportedException("PIO: StoreIndirect not yet implemented");
            case InlineAsm arg: assembly.Add(PIOAsmLine.MakeRaw(arg.Code)); break;
            case DebugLine arg:
                if (!string.IsNullOrEmpty(arg.SourceFile)) EmitComment($"{arg.SourceFile}:{arg.Line}: {arg.Text}");
                else EmitComment($"Line {arg.Line}: {arg.Text}");
                break;
            case UARTSendString: break;
            case ArrayLoad: break;
            case ArrayStore: break;
        }
    }

    private void CompileCopy(Copy arg)
    {
        string dst = ResolveOperand(arg.Dst);
        if (arg.Src is Constant c)
            Emit("SET", dst, (c.Value & 0x1F).ToString());
        else
            Emit("MOV", dst, ResolveOperand(arg.Src));
    }

    private void CompileJumpIfZero(JumpIfZero arg)
    {
        if (arg.Condition is Constant c)
        {
            if (c.Value == 0) Emit("JMP", arg.Target);
            return;
        }

        string reg = ResolveOperand(arg.Condition);
        if (reg == "X") Emit("JMP", "!X", arg.Target);
        else if (reg == "Y") Emit("JMP", "!Y", arg.Target);
        else throw new InvalidOperationException("PIO JMP condition must be X or Y");
    }

    private void CompileJumpIfNotZero(JumpIfNotZero arg)
    {
        if (arg.Condition is Constant c)
        {
            if (c.Value != 0) Emit("JMP", arg.Target);
            return;
        }

        string reg = ResolveOperand(arg.Condition);
        string skip = MakeLabel("skip_jnz");
        if (reg == "X")
        {
            Emit("JMP", "!X", skip);
            Emit("JMP", arg.Target);
        }
        else if (reg == "Y")
        {
            Emit("JMP", "!Y", skip);
            Emit("JMP", arg.Target);
        }

        EmitLabel(skip);
    }

    private void CompileUnary(Unary arg)
    {
        string dst = ResolveOperand(arg.Dst);
        string src = ResolveOperand(arg.Src);
        if (arg.Op == PyMCU.IR.UnaryOp.BitNot) Emit("MOV", dst, "!" + src);
        else throw new NotSupportedException("PIO Unary op not supported");
    }

    private void CompileBinary(Binary arg)
    {
        string dst = ResolveOperand(arg.Dst);
        string src1 = ResolveOperand(arg.Src1);

        if (arg.Op == PyMCU.IR.BinaryOp.Sub)
        {
            if (src1 == dst && arg.Src2 is Constant c && c.Value == 1)
            {
                string next = MakeLabel("next");
                if (dst == "X") Emit("JMP", "X--", next);
                else if (dst == "Y") Emit("JMP", "Y--", next);
                else throw new InvalidOperationException("PIO decrement only works on X or Y registers");
                EmitLabel(next);
            }
            else throw new NotSupportedException("PIO: subtraction only supported as decrement (x = x - 1)");
        }
        else throw new NotSupportedException("PIO: Arithmetic operations are not supported by PIO hardware.");
    }

    private void CompileCall(Call arg)
    {
        switch (arg.FunctionName)
        {
            case "__pio_pull":
            {
                string block = "BLOCK";
                if (arg.Args.Count > 0 && arg.Args[0] is Constant c && c.Value == 0) block = "NOBLOCK";
                Emit("PULL", block);
                break;
            }
            case "__pio_push":
            {
                string block = "BLOCK";
                if (arg.Args.Count > 0 && arg.Args[0] is Constant c && c.Value == 0) block = "NOBLOCK";
                Emit("PUSH", block);
                break;
            }
            case "__pio_out":
                Emit("OUT", ResolveOperand(arg.Args[0]), ResolveOperand(arg.Args[1]));
                break;
            case "__pio_in":
                Emit("IN", ResolveOperand(arg.Args[0]), ResolveOperand(arg.Args[1]));
                break;
            case "__pio_wait":
                Emit("WAIT", ResolveOperand(arg.Args[0]), ResolveOperand(arg.Args[1]), ResolveOperand(arg.Args[2]));
                break;
            case "delay":
                if (assembly.Count > 0 && assembly[^1].Type == PIOAsmLine.LineType.Instruction)
                {
                    if (arg.Args.Count > 0 && arg.Args[0] is Constant c)
                        assembly[^1].Delay = c.Value;
                }

                break;
        }
    }
}