[device]
name = "PIC16F84A"
arch = "pic14"  # Arquitectura base para gpasm
family = "midrange"

[memory]
flash_size = 1024
ram_start = 0x0C
ram_end = 0x4F
stack_method = "software" # O "hardware" si soportas el stack limitado del PIC

[toolchain]
gpasm_flags = ["-p16f84a"]
linker_script = "16f84a_g.lkr"

[registers]
status = 0x03
porta = 0x05
portb = 0x06