; Generated by pymcuc (PIC14 Backend)
	PROCESSOR 16F84A
	#include <xc.inc>

	__CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _CP_OFF

; --- Data Section ---
	UDATA

; --- Code Section ---
	CODE
	ORG 0x00
	GOTO	main

main:
	MOVLW	0x02
	RETURN
	END
