# -----------------------------------------------------------------------------
# PyMCU CLI Driver
# Copyright (C) 2026 Ivan Montiel Cardona and the PyMCU Project Authors
# SPDX-License-Identifier: MIT
# -----------------------------------------------------------------------------
# SAFETY WARNING / HIGH RISK ACTIVITIES:
# THE SOFTWARE IS NOT DESIGNED, MANUFACTURED, OR INTENDED FOR USE IN HAZARDOUS
# ENVIRONMENTS REQUIRING FAIL-SAFE PERFORMANCE, SUCH AS IN THE OPERATION OF
# NUCLEAR FACILITIES, AIRCRAFT NAVIGATION OR COMMUNICATION SYSTEMS, AIR
# TRAFFIC CONTROL, DIRECT LIFE SUPPORT MACHINES, OR WEAPONS SYSTEMS.
# -----------------------------------------------------------------------------

import importlib.util
from pathlib import Path

import tomlkit
import typer
from rich.console import Console

console = Console()


def sync():
    """Sync pyproject.toml board config with dist/_generated/board.py.

    Run this after changing the 'board' key in [tool.pymcu] so that IDEs
    can resolve 'import board' before the next full build.
    """
    toml_path = Path("pyproject.toml")
    if not toml_path.exists():
        console.print("[red]Error: No pyproject.toml found in the current directory.[/red]")
        raise typer.Exit(code=1)

    doc = tomlkit.loads(toml_path.read_text())
    pymcu_cfg = doc.get("tool", {}).get("pymcu", {})

    board = pymcu_cfg.get("board")
    stdlib_list = list(pymcu_cfg.get("stdlib", []))

    if not board:
        console.print(
            "[yellow]No 'board' key in [tool.pymcu] — nothing to sync.[/yellow]\n"
            "[dim]Add 'board = \"arduino_uno\"' (or similar) to your pyproject.toml.[/dim]"
        )
        raise typer.Exit(code=0)

    if not stdlib_list:
        console.print(
            "[yellow]No 'stdlib' in [tool.pymcu] — nothing to sync.[/yellow]\n"
            "[dim]Add stdlib = [\"micropython\"] or [\"circuitpython\"] to your pyproject.toml.[/dim]"
        )
        raise typer.Exit(code=0)

    flavor = stdlib_list[0]
    module_name = f"pymcu_{flavor}.boards.{board}"

    spec = importlib.util.find_spec(module_name)
    if spec is None or spec.origin is None:
        console.print(
            f"[red]Error: Board '{board}' not found in pymcu-{flavor}.[/red]\n"
            f"[dim]Make sure pymcu-{flavor} is installed and '{board}' is a valid board name.[/dim]"
        )
        raise typer.Exit(code=1)

    board_source = Path(spec.origin).read_text()

    generated_dir = Path("dist") / "_generated"
    generated_dir.mkdir(parents=True, exist_ok=True)

    header = (
        f"# Auto-generated by pymcu sync — do not edit\n"
        f"# board: {board}  flavor: {flavor}\n\n"
    )
    board_py = generated_dir / "board.py"
    board_py.write_text(header + board_source)

    console.print(
        f"[bold green]+[/bold green] Synced board '[bold]{board}[/bold]' "
        f"({flavor}) → {board_py}"
    )
