package dev.begeistert.pymcu.stdlib

import com.intellij.openapi.diagnostic.Logger
import dev.begeistert.pymcu.resolver.findSitePackages
import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.exists

/**
 * Handles the only piece of dynamic file generation needed for IDE support:
 * `dist/_generated/board.py` for CircuitPython projects.
 *
 * All other import resolution is done by pointing PyCharm at the REAL installed
 * source packages in .venv via PyMcuAdditionalLibraryRootsProvider — no generated
 * stubs needed, full traceability to implementation.
 *
 * Additionally, removes legacy .pyi stub files that may have been written by
 * previous versions of the plugin.
 */
object PyMcuStubInstaller {

    private val log = Logger.getInstance(PyMcuStubInstaller::class.java)

    /**
     * Pre-generates `dist/_generated/board.py` so PyCharm can resolve
     * `import board` before the first build. Cleans up legacy .pyi files.
     * Returns the site-packages path if a board.py was written, otherwise null.
     */
    fun install(basePath: String, stdlib: List<String>, board: String?): Path? {
        val sp = findSitePackages(basePath)

        // Clean up any legacy .pyi stubs from older plugin versions
        if (sp != null) cleanLegacyStubs(sp)

        return if ("circuitpython" in stdlib) {
            val wrote = generateDistBoard(basePath, board, sp)
            if (wrote) sp else null
        } else {
            null
        }
    }

    /** Remove .pyi files previously generated by older plugin versions in site-packages. */
    private fun cleanLegacyStubs(sitePackages: Path) {
        val legacyStubs = listOf(
            "board.pyi", "digitalio.pyi", "analogio.pyi", "busio.pyi",
            "machine.pyi", "utime.pyi", "neopixel.pyi"
        )
        for (name in legacyStubs) {
            val f = sitePackages.resolve(name).toFile()
            if (f.exists()) {
                f.delete()
                log.info("PyMCU: removed legacy stub $name")
            }
        }
    }

    /**
     * Copies the board constants file from the installed `pymcu_circuitpython`
     * package into `<projectRoot>/dist/_generated/board.py`.
     *
     * This allows PyCharm to resolve `import board` via the library roots provider
     * even before the first `pymcu build` run.
     */
    private fun generateDistBoard(basePath: String, board: String?, sitePackages: Path?): Boolean {
        val pkg     = sitePackages?.resolve("pymcu_circuitpython")
        val boardId = board?.replace("-", "_") ?: "arduino_uno"
        val source  = when {
            pkg != null -> listOf(
                pkg.resolve("boards/$boardId.py"),
                pkg.resolve("boards/arduino_uno.py")
            ).firstOrNull { it.exists() }
            else -> null
        }
        if (source == null) {
            log.debug("PyMCU: no board constants file found — skipping dist/_generated/board.py")
            return false
        }
        return try {
            val generatedDir = Path.of(basePath, "dist", "_generated")
            Files.createDirectories(generatedDir)
            Files.writeString(generatedDir.resolve("board.py"), source.toFile().readText())
            log.info("PyMCU: wrote dist/_generated/board.py for `import board` resolution")
            true
        } catch (e: Exception) {
            log.warn("PyMCU: failed to write dist/_generated/board.py", e)
            false
        }
    }
}
