using PyMCU.Backend.Analysis;
using PyMCU.Common;
using PyMCU.IR;

namespace PyMCU.Backend.Targets.PIC12;

public class PIC12CodeGen(DeviceConfig cfg) : CodeGen
{
    private readonly List<PIC12AsmLine> _assembly = [];
    private readonly Dictionary<string, int> _symbolTable = new();
    private Dictionary<string, int> _stackLayout = new();
    private int _ramHead = 0x08;
    private int _labelCounter;

    private string MakeLabel(string prefix) => $"{prefix}_{_labelCounter++}";

    private void Emit(string m) => _assembly.Add(PIC12AsmLine.MakeInstruction(m));
    private void Emit(string m, string o1) => _assembly.Add(PIC12AsmLine.MakeInstruction(m, o1));
    private void Emit(string m, string o1, string o2) => _assembly.Add(PIC12AsmLine.MakeInstruction(m, o1, o2));
    private void EmitLabel(string l) => _assembly.Add(PIC12AsmLine.MakeLabel(l));
    private void EmitComment(string c) => _assembly.Add(PIC12AsmLine.MakeComment(c));
    private void EmitRaw(string t) => _assembly.Add(PIC12AsmLine.MakeRaw(t));

    public override void EmitContextSave()
    {
    }

    public override void EmitContextRestore()
    {
    }

    public override void EmitInterruptReturn()
    {
    }

    private string ResolveAddress(Val val)
    {
        if (val is Constant c) return $"0x{c.Value & 0xFF:X2}";
        if (val is MemoryAddress mem) return $"0x{mem.Address:X2}";
        string name = val switch { Variable v => v.Name, Temporary t => t.Name, _ => "" };
        if (_stackLayout.ContainsKey(name)) return name;
        return GetOrAllocVariable(name);
    }

    private string GetOrAllocVariable(string name)
    {
        if (!_symbolTable.ContainsKey(name))
        {
            _symbolTable[name] = _ramHead++;
            EmitRaw($"{name} EQU 0x{_symbolTable[name]:X2}");
        }

        return name;
    }

    private void LoadIntoW(Val val)
    {
        if (val is Constant c)
        {
            Emit("MOVLW", $"0x{c.Value & 0xFF:X2}");
        }
        else
        {
            string addr = ResolveAddress(val);
            // TRIS registers are write-only on base-line, use shadow
            if (addr == "0x85") addr = GetOrAllocVariable("__tris_shadow_5");
            else if (addr == "0x86") addr = GetOrAllocVariable("__tris_shadow_6");
            else if (addr == "0x87") addr = GetOrAllocVariable("__tris_shadow_7");
            Emit("MOVF", addr, "W");
        }
    }

    private void StoreWInto(Val val)
    {
        string addr = ResolveAddress(val);

        if (addr == "0x81")
        {
            Emit("OPTION");
            return;
        }

        int trisReg = -1;
        if (addr == "0x85") trisReg = 5;
        else if (addr == "0x86") trisReg = 6;
        else if (addr == "0x87") trisReg = 7;

        if (trisReg != -1)
        {
            Emit("TRIS", trisReg.ToString());
            string shadow = GetOrAllocVariable($"__tris_shadow_{trisReg}");
            Emit("MOVWF", shadow);
            return;
        }

        Emit("MOVWF", addr);
    }

    public override void Compile(ProgramIR program, TextWriter output)
    {
        _assembly.Clear();

        var allocator = new StackAllocator();
        var (offsets, _) = allocator.Allocate(program);
        _stackLayout = offsets;

        EmitComment("Generated by pymcuc for PIC12 (Base-line)");
        string chipUpper = cfg.Chip.ToUpperInvariant();
        EmitRaw($"\tPROCESSOR {chipUpper}");
        EmitRaw("\t#include <xc.inc>");

        EmitComment("--- Compiled Stack (Overlays) ---");
        EmitRaw("_stack_base EQU 0x08");
        foreach (var (name, offset) in _stackLayout)
            EmitRaw($"{name} EQU _stack_base + {offset}");

        EmitRaw("\tORG 0x00");
        Emit("GOTO", "main");

        foreach (var func in program.Functions)
            CompileFunction(func);

        EmitRaw("\tEND");

        foreach (var line in _assembly)
            output.WriteLine(line.ToString());
    }

    private void CompileFunction(Function func)
    {
        EmitLabel(func.Name);
        foreach (var instr in func.Body)
            CompileInstruction(instr);
    }

    private void CompileInstruction(Instruction instr)
    {
        switch (instr)
        {
            case Return arg: CompileReturn(arg); break;
            case Copy arg: CompileCopy(arg); break;
            case Unary arg: CompileUnary(arg); break;
            case Binary arg: CompileBinary(arg); break;
            case Jump arg: Emit("GOTO", arg.Target); break;
            case JumpIfZero arg: CompileJumpIfZero(arg); break;
            case JumpIfNotZero arg: CompileJumpIfNotZero(arg); break;
            case Label arg: EmitLabel(arg.Name); break;
            case Call arg: CompileCall(arg); break;
            case BitSet arg: CompileBitSet(arg); break;
            case BitClear arg: CompileBitClear(arg); break;
            case BitCheck arg: CompileBitCheck(arg); break;
            case BitWrite arg: CompileBitWrite(arg); break;
            case JumpIfBitSet arg: CompileJumpIfBitSet(arg); break;
            case JumpIfBitClear arg: CompileJumpIfBitClear(arg); break;
            case JumpIfEqual arg: CompileJumpIfEqual(arg); break;
            case JumpIfNotEqual arg: CompileJumpIfNotEqual(arg); break;
            case JumpIfLessThan arg: CompileJumpIfLessThan(arg); break;
            case JumpIfLessOrEqual arg: CompileJumpIfLessOrEqual(arg); break;
            case JumpIfGreaterThan arg: CompileJumpIfGreaterThan(arg); break;
            case JumpIfGreaterOrEqual arg: CompileJumpIfGreaterOrEqual(arg); break;
            case AugAssign: throw new NotSupportedException("PIC12: AugAssign is not yet implemented");
            case LoadIndirect:
                throw new NotSupportedException("PIC12: pointer dereference (LoadIndirect) is not supported");
            case StoreIndirect:
                throw new NotSupportedException("PIC12: pointer dereference (StoreIndirect) is not supported");
            case InlineAsm arg: _assembly.Add(PIC12AsmLine.MakeRaw(arg.Code)); break;
            case DebugLine arg:
                if (!string.IsNullOrEmpty(arg.SourceFile))
                    EmitComment($"{arg.SourceFile}:{arg.Line}: {arg.Text}");
                else
                    EmitComment($"Line {arg.Line}: {arg.Text}");
                break;
            // AVR-only; no-op here
            case UARTSendString: break;
            case ArrayLoad: break;
            case ArrayStore: break;
        }
    }

    private void CompileReturn(Return arg)
    {
        LoadIntoW(arg.Value);
        Emit("RETLW", "0"); // PIC12 baseline has no RETURN, use RETLW
    }

    private void CompileCopy(Copy arg)
    {
        LoadIntoW(arg.Src);
        StoreWInto(arg.Dst);
    }

    private void CompileUnary(Unary arg)
    {
        LoadIntoW(arg.Src);
        switch (arg.Op)
        {
            case PyMCU.IR.UnaryOp.BitNot:
                Emit("XORLW", "0xFF");
                break;
            case PyMCU.IR.UnaryOp.Not:
                Emit("XORLW", "1");
                Emit("ANDLW", "1");
                break;
            case PyMCU.IR.UnaryOp.Neg:
                Emit("XORLW", "0xFF");
            {
                string temp = GetOrAllocVariable("__neg_temp");
                Emit("MOVWF", temp);
                Emit("MOVLW", "1");
                Emit("ADDWF", temp, "W");
            }
                break;
        }

        StoreWInto(arg.Dst);
    }

    private void CompileBinary(Binary arg)
    {
        LoadIntoW(arg.Src1);
        string right = ResolveAddress(arg.Src2);

        switch (arg.Op)
        {
            case PyMCU.IR.BinaryOp.Add:
                if (arg.Src2 is Constant)
                {
                    string temp = GetOrAllocVariable("__add_temp");
                    Emit("MOVWF", temp);
                    Emit("MOVLW", right);
                    Emit("ADDWF", temp, "W");
                }
                else Emit("ADDWF", right, "W");

                break;

            case PyMCU.IR.BinaryOp.Sub:
                if (arg.Src2 is Constant)
                {
                    string temp = GetOrAllocVariable("__sub_temp");
                    Emit("MOVWF", temp);
                    Emit("MOVLW", $"(0x100 - ({right})) & 0xFF");
                    Emit("ADDWF", temp, "W");
                }
                else
                {
                    LoadIntoW(arg.Src2);
                    string left = ResolveAddress(arg.Src1);
                    Emit("SUBWF", left, "W");
                }

                break;

            case PyMCU.IR.BinaryOp.BitAnd:
                if (arg.Src2 is Constant) Emit("ANDLW", right);
                else Emit("ANDWF", right, "W");
                break;

            case PyMCU.IR.BinaryOp.BitOr:
                if (arg.Src2 is Constant) Emit("IORLW", right);
                else Emit("IORWF", right, "W");
                break;

            case PyMCU.IR.BinaryOp.BitXor:
                if (arg.Src2 is Constant) Emit("XORLW", right);
                else Emit("XORWF", right, "W");
                break;

            case PyMCU.IR.BinaryOp.LShift:
            case PyMCU.IR.BinaryOp.RShift:
            {
                StoreWInto(arg.Dst);
                string dstAddr = ResolveAddress(arg.Dst);
                string rotateOp = arg.Op == PyMCU.IR.BinaryOp.LShift ? "RLF" : "RRF";

                if (arg.Src2 is Constant c2)
                {
                    int shiftCount = c2.Value & 0x07;
                    for (int i = 0; i < shiftCount; i++)
                    {
                        Emit("BCF", "STATUS", "0");
                        Emit(rotateOp, dstAddr, "F");
                    }
                }
                else
                {
                    string countAddr = ResolveAddress(arg.Src2);
                    string loopLabel = MakeLabel("shift");
                    string doneLabel = MakeLabel("shift_done");
                    Emit("MOVF", countAddr, "W");
                    Emit("BTFSC", "STATUS", "2");
                    Emit("GOTO", doneLabel);
                    EmitLabel(loopLabel);
                    Emit("BCF", "STATUS", "0");
                    Emit(rotateOp, dstAddr, "F");
                    Emit("DECFSZ", countAddr, "F");
                    Emit("GOTO", loopLabel);
                    EmitLabel(doneLabel);
                }

                return; // Already stored in dst
            }

            case PyMCU.IR.BinaryOp.Equal:
            case PyMCU.IR.BinaryOp.NotEqual:
            case PyMCU.IR.BinaryOp.LessThan:
            case PyMCU.IR.BinaryOp.LessEqual:
            case PyMCU.IR.BinaryOp.GreaterThan:
            case PyMCU.IR.BinaryOp.GreaterEqual:
            {
                LoadIntoW(arg.Src2);
                string left = ResolveAddress(arg.Src1);
                Emit("SUBWF", left, "W");
                string dstAddr = ResolveAddress(arg.Dst);
                Emit("CLRF", dstAddr);

                switch (arg.Op)
                {
                    case PyMCU.IR.BinaryOp.Equal: Emit("BTFSC", "STATUS", "2"); break;
                    case PyMCU.IR.BinaryOp.NotEqual: Emit("BTFSS", "STATUS", "2"); break;
                    case PyMCU.IR.BinaryOp.LessThan: Emit("BTFSS", "STATUS", "0"); break;
                    case PyMCU.IR.BinaryOp.GreaterEqual: Emit("BTFSC", "STATUS", "0"); break;
                    case PyMCU.IR.BinaryOp.GreaterThan:
                    {
                        string lblSkip = MakeLabel("L_GT");
                        Emit("BTFSS", "STATUS", "0");
                        Emit("GOTO", lblSkip);
                        Emit("BTFSC", "STATUS", "2");
                        Emit("GOTO", lblSkip);
                        Emit("INCF", dstAddr, "F");
                        EmitLabel(lblSkip);
                        return;
                    }
                    case PyMCU.IR.BinaryOp.LessEqual:
                    {
                        var lblSet = MakeLabel("L_LE");
                        var lblSkip = MakeLabel("L_LES");
                        Emit("BTFSS", "STATUS", "0");
                        Emit("GOTO", lblSet);
                        Emit("BTFSS", "STATUS", "2");
                        Emit("GOTO", lblSkip);
                        EmitLabel(lblSet);
                        Emit("INCF", dstAddr, "F");
                        EmitLabel(lblSkip);
                        return;
                    }
                }

                Emit("INCF", dstAddr, "F");
                return;
            }
        }

        StoreWInto(arg.Dst);
    }

    private void CompileJumpIfZero(JumpIfZero arg)
    {
        LoadIntoW(arg.Condition);
        Emit("IORLW", "0");
        Emit("BTFSC", "STATUS", "2");
        Emit("GOTO", arg.Target);
    }

    private void CompileJumpIfNotZero(JumpIfNotZero arg)
    {
        LoadIntoW(arg.Condition);
        Emit("IORLW", "0");
        Emit("BTFSS", "STATUS", "2");
        Emit("GOTO", arg.Target);
    }

    private void CompileCall(Call arg)
    {
        Emit("CALL", arg.FunctionName);
        if (arg.Dst is not NoneVal) StoreWInto(arg.Dst);
    }

    private void CompileBitSet(BitSet arg)
    {
        string addr = ResolveAddress(arg.Target);
        int trisReg = addr == "0x85" ? 5 : addr == "0x86" ? 6 : addr == "0x87" ? 7 : -1;

        if (trisReg != -1)
        {
            string shadow = GetOrAllocVariable($"__tris_shadow_{trisReg}");
            Emit("BSF", shadow, arg.Bit.ToString());
            Emit("MOVF", shadow, "W");
            Emit("TRIS", trisReg.ToString());
        }
        else Emit("BSF", addr, arg.Bit.ToString());
    }

    private void CompileBitClear(BitClear arg)
    {
        string addr = ResolveAddress(arg.Target);
        int trisReg = addr == "0x85" ? 5 : addr == "0x86" ? 6 : addr == "0x87" ? 7 : -1;

        if (trisReg != -1)
        {
            string shadow = GetOrAllocVariable($"__tris_shadow_{trisReg}");
            Emit("BCF", shadow, arg.Bit.ToString());
            Emit("MOVF", shadow, "W");
            Emit("TRIS", trisReg.ToString());
        }
        else Emit("BCF", addr, arg.Bit.ToString());
    }

    private void CompileBitCheck(BitCheck arg)
    {
        string addr = ResolveAddress(arg.Source);
        if (addr == "0x85") addr = GetOrAllocVariable("__tris_shadow_5");
        else if (addr == "0x86") addr = GetOrAllocVariable("__tris_shadow_6");
        else if (addr == "0x87") addr = GetOrAllocVariable("__tris_shadow_7");

        string dst = ResolveAddress(arg.Dst);
        Emit("CLRF", dst);
        Emit("BTFSC", addr, arg.Bit.ToString());
        Emit("INCF", dst, "F");
    }

    private void CompileBitWrite(BitWrite arg)
    {
        string addr = ResolveAddress(arg.Target);
        int trisReg = addr == "0x85" ? 5 : addr == "0x86" ? 6 : addr == "0x87" ? 7 : -1;

        LoadIntoW(arg.Src);
        Emit("IORLW", "0");
        string lblSet = MakeLabel("bit_set");
        string lblEnd = MakeLabel("bit_end");
        Emit("BTFSS", "STATUS", "2");
        Emit("GOTO", lblSet);

        if (trisReg != -1)
        {
            string shadow = GetOrAllocVariable($"__tris_shadow_{trisReg}");
            Emit("BCF", shadow, arg.Bit.ToString());
            Emit("MOVF", shadow, "W");
            Emit("TRIS", trisReg.ToString());
        }
        else Emit("BCF", addr, arg.Bit.ToString());

        Emit("GOTO", lblEnd);
        EmitLabel(lblSet);

        if (trisReg != -1)
        {
            string shadow = GetOrAllocVariable($"__tris_shadow_{trisReg}");
            Emit("BSF", shadow, arg.Bit.ToString());
            Emit("MOVF", shadow, "W");
            Emit("TRIS", trisReg.ToString());
        }
        else Emit("BSF", addr, arg.Bit.ToString());

        EmitLabel(lblEnd);
    }

    private void CompileJumpIfBitSet(JumpIfBitSet arg)
    {
        string addr = ResolveAddress(arg.Source);
        Emit("BTFSC", addr, arg.Bit.ToString());
        Emit("GOTO", arg.Target);
    }

    private void CompileJumpIfBitClear(JumpIfBitClear arg)
    {
        string addr = ResolveAddress(arg.Source);
        Emit("BTFSS", addr, arg.Bit.ToString());
        Emit("GOTO", arg.Target);
    }

    private void CompileJumpIfEqual(JumpIfEqual arg)
    {
        if (arg.Src2 is Constant c2 && c2.Value >= 0 && c2.Value <= 255)
        {
            string src1 = ResolveAddress(arg.Src1);
            Emit("MOVF", src1, "W");
            Emit("XORLW", $"0x{c2.Value:X2}");
            Emit("BTFSC", "STATUS", "2");
            Emit("GOTO", arg.Target);
            return;
        }

        LoadIntoW(arg.Src2);
        string s1 = ResolveAddress(arg.Src1);
        Emit("SUBWF", s1, "W");
        Emit("BTFSC", "STATUS", "2");
        Emit("GOTO", arg.Target);
    }

    private void CompileJumpIfNotEqual(JumpIfNotEqual arg)
    {
        if (arg.Src2 is Constant c2 && c2.Value >= 0 && c2.Value <= 255)
        {
            string src1 = ResolveAddress(arg.Src1);
            Emit("MOVF", src1, "W");
            Emit("XORLW", $"0x{c2.Value:X2}");
            Emit("BTFSS", "STATUS", "2");
            Emit("GOTO", arg.Target);
            return;
        }

        LoadIntoW(arg.Src2);
        string s1 = ResolveAddress(arg.Src1);
        Emit("SUBWF", s1, "W");
        Emit("BTFSS", "STATUS", "2");
        Emit("GOTO", arg.Target);
    }

    private void CompileJumpIfLessThan(JumpIfLessThan arg)
    {
        if (arg.Src2 is Constant c2 && c2.Value >= 0 && c2.Value <= 255)
        {
            int k = c2.Value;
            if (k == 0) return;
            string src1 = ResolveAddress(arg.Src1);
            Emit("MOVF", src1, "W");
            Emit("SUBLW", $"0x{k - 1:X2}");
            Emit("BTFSC", "STATUS", "0");
            Emit("GOTO", arg.Target);
            return;
        }

        LoadIntoW(arg.Src2);
        string s1 = ResolveAddress(arg.Src1);
        Emit("SUBWF", s1, "W");
        Emit("BTFSS", "STATUS", "0");
        Emit("GOTO", arg.Target);
    }

    private void CompileJumpIfLessOrEqual(JumpIfLessOrEqual arg)
    {
        if (arg.Src2 is Constant c2 && c2.Value >= 0 && c2.Value <= 255)
        {
            string src1 = ResolveAddress(arg.Src1);
            Emit("MOVF", src1, "W");
            Emit("SUBLW", $"0x{c2.Value:X2}");
            Emit("BTFSC", "STATUS", "0");
            Emit("GOTO", arg.Target);
            return;
        }

        LoadIntoW(arg.Src1);
        string src2Addr = ResolveAddress(arg.Src2);
        Emit("SUBWF", src2Addr, "W");
        Emit("BTFSC", "STATUS", "0");
        Emit("GOTO", arg.Target);
    }

    private void CompileJumpIfGreaterThan(JumpIfGreaterThan arg)
    {
        if (arg.Src2 is Constant c2 && c2.Value >= 0 && c2.Value <= 255)
        {
            string src1 = ResolveAddress(arg.Src1);
            Emit("MOVF", src1, "W");
            Emit("SUBLW", $"0x{c2.Value:X2}");
            Emit("BTFSS", "STATUS", "0");
            Emit("GOTO", arg.Target);
            return;
        }

        LoadIntoW(arg.Src1);
        string src2Addr = ResolveAddress(arg.Src2);
        Emit("SUBWF", src2Addr, "W");
        Emit("BTFSS", "STATUS", "0");
        Emit("GOTO", arg.Target);
    }

    private void CompileJumpIfGreaterOrEqual(JumpIfGreaterOrEqual arg)
    {
        if (arg.Src2 is Constant c2 && c2.Value >= 0 && c2.Value <= 255)
        {
            int k = c2.Value;
            if (k == 0)
            {
                Emit("GOTO", arg.Target);
                return;
            }

            string src1 = ResolveAddress(arg.Src1);
            Emit("MOVF", src1, "W");
            Emit("SUBLW", $"0x{k - 1:X2}");
            Emit("BTFSS", "STATUS", "0");
            Emit("GOTO", arg.Target);
            return;
        }

        LoadIntoW(arg.Src2);
        string s1 = ResolveAddress(arg.Src1);
        Emit("SUBWF", s1, "W");
        Emit("BTFSC", "STATUS", "0");
        Emit("GOTO", arg.Target);
    }
}