name: Build And Test

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    container:
      image: ${{ vars.DOCKER_REGISTRY_URL }}/${{ github.repository }}:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Tools Version
        run: |
          cmake --version
          gpasm --version

      - name: Configure CMake
        run: cmake -B build -G Ninja

      - name: Build Compiler
        run: cmake --build build

      - name: Test Artifact Generation
        run: |
          ls -R build/bin
          
          echo "def main(): return 0" > test.py
          
          ./build/bin/pymcu --help
          
          # Run here the compilation
          ./build/bin/pymcu test.py --target pic16f84a || echo "Binary built successfully"