name: Unit Tests

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Unit Tests
    container:
      image: ${{ vars.DOCKER_REGISTRY_URL }}/${{ github.repository }}:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Tools Version
        run: |
          cmake --version
          gpasm --version
          gcc -- version

      - name: Configure CMake
        run: cmake -B build -G Ninja

      - name: Build Compiler
        run: cmake --build build

      - name: Run Unit Tests
        run: ctest --test-dir build --output-on-failure